### ISSUE TITLE
Any reason element-web's dependencies couldn't have nodejs-16 allowed?

### ISSUE THREAD

**Issue by realkinetix** [SFTtech/gentoo-overlay#5]
I couldn't have a server on mine stuck below nodejs 16 LTS any longer, so I updated element-web's RDEPEND to:

<net-libs/nodejs-18

I haven't done a full emerge -e on element-web or anything, so there could be something else that would break.  So far, so good, on this system of mine, though.

Anyhow, thanks of course for providing this repo and the element apps!

**Comment by TheJJ** [comment]
Hey! The reason is stated in the comment above that requirement:
```
# maybe nodejs version needs to be limited according to these compatibilities:
# https://github.com/node-gfx/node-canvas-prebuilt/releases
# https://nodejs.org/en/download/releases/
```

element did depend on this node-canvas-prebuilt thingy, but apparently not any more. I've updated my node to v18 and updated element-web/desktop, and it works :)

so I think we can drop that version limiting, but when testing, i ran into discovering nodejs/node-gyp/issues/2750
let's see how deep we need to dig into this rabbit hole...

thanks for the hint!

**Comment by realkinetix** [comment]
Well, I hope that turns out OK. I only went as far as 16 as it's LTS.

**Comment by TheJJ** [comment]
Turns out it didn't so far - surprise!  I've now fixed it so it does work with the latest nodejs version... by patching 3 layers of nested dependency fetching - see 3eb701ffab15e451493485a8d0953860524b50b3. Please check if it works for you, too.
